# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - choai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://choimirai.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b92ebdf5b36349488affe196f0aead34 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2c593de6cc244896a5a6e865abde2913 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: choimirai.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b92ebdf5b36349488affe196f0aead34 }}/aitutor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'choai'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a3b63f931aa54a7c8d6f329f764e004a }}
        images: 'choimirai.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b92ebdf5b36349488affe196f0aead34 }}/aitutor:${{ github.sha }}'